Relatório de Patentes [RES-14]
CinCoders/research-back pull request #21
Opened 2024-03-20 18:47 UTC by karensamara

2024-04-03 19:49 UTC, weltonfelix requested changes

2024-04-03 19:50 UTC, yuricdb requested changes

2024-04-08 18:36 UTC, dcruzb approved these changes

2024-04-08 18:36 UTC, dcruzb commented on downloadedFiles/xmls/3847692220708299.xml
This file should not be uploaded

2024-10-07 13:51 UTC, dcruzb approved these changes

2024-10-07 13:52 UTC, merged